### ISSUE TITLE
Can't run under RubyGems 2.5.1 and Ruby 2.3.0

### ISSUE THREAD

**Issue by tvdeyen** [skywinder/github-changelog-generator#325]
### What have I done

Following the README, I installed via `gem install github_changelog_generator` without any problems

#### In the root of the repo:

```
git remote -v
origin	git@github.com:AlchemyCMS/alchemy_cms.git
```

#### Running:

```
github_changelog_generator
```

#### I get following error:

```
/Users/tvd/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fe019ccbdf0 github_api-0.13.1> (NoMethodError)
	from /Users/tvd/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/tvd/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/tvd/.rvm/gems/ruby-2.3.0@alchemy/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator.rb:3:in `<top (required)>'
	from /Users/tvd/.rvm/gems/ruby-2.3.0@alchemy/gems/github_changelog_generator-1.10.1/bin/github_changelog_generator:3:in `require_relative'
	from /Users/tvd/.rvm/gems/ruby-2.3.0@alchemy/gems/github_changelog_generator-1.10.1/bin/github_changelog_generator:3:in `<top (required)>'
	from /Users/tvd/.rvm/gems/ruby-2.3.0@alchemy/bin/github_changelog_generator:23:in `load'
	from /Users/tvd/.rvm/gems/ruby-2.3.0@alchemy/bin/github_changelog_generator:23:in `<main>'
	from /Users/tvd/.rvm/gems/ruby-2.3.0@alchemy/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tvd/.rvm/gems/ruby-2.3.0@alchemy/bin/ruby_executable_hooks:15:in `<main>'
```

#### Even with a GitHub token:

```
github_changelog_generator --token <TOKEN>
```

I get the above error.

### My env

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21

$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

$ gem -v
2.5.1

$ github_changelog_generator -v
/Users/tvd/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fe409489d10 github_api-0.13.1> (NoMethodError)
...
:(
```

**Comment by olleolleolle** [comment]
It's not you, it's Rubygems + 2.3.0 that gives you this headache. @jesjos got this weird error yesterday - on a completely different project. 

His workaround was "for this, use rvm with a slightly earlier Ruby version". Something like rvm 2.2 do github_changelog_generator.

**Comment by Chosko** [comment]
I'm running in the same issue

```
/home/chosko/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x760188 github_api-0.13.1> (NoMethodError)
	from /home/chosko/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /home/chosko/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /home/chosko/.rvm/gems/ruby-2.3.0/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator.rb:3:in `<top (required)>'
	from /home/chosko/.rvm/gems/ruby-2.3.0/gems/github_changelog_generator-1.10.1/bin/github_changelog_generator:3:in `require_relative'
	from /home/chosko/.rvm/gems/ruby-2.3.0/gems/github_changelog_generator-1.10.1/bin/github_changelog_generator:3:in `<top (required)>'
	from /home/chosko/.rvm/gems/ruby-2.3.0/bin/github_changelog_generator:23:in `load'
	from /home/chosko/.rvm/gems/ruby-2.3.0/bin/github_changelog_generator:23:in `<main>'
	from /home/chosko/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/chosko/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

with

```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

$ gem -v  
2.5.1
```

**Comment by tvdeyen** [comment]
Confirmed working with Ruby 2.2 and Rubygems 2.4.8

**Comment by perlun** [comment]
I think it's a bit more sophisticated than that. I.e., it's not _completely_ broken with Ruby 2.3.0, only under certain circumstances.

When running `github_changelog_generator` inside a project folder, I get the same error. If I change to another folder and manually specify a `-u user -p project`, it runs without problems.

If I run the exact same command inside the project folder, it fails.

The project in question is a pretty standard project, with a `Gemfile` (i.e. using bundler). I am using `rvm` on OS X.

**Comment by olleolleolle** [comment]
@perlun just patched this defect Rubygems (not yet released). See https://github.com/rubygems/rubygems/pull/1558 for more details.

Closing this issue. Thanks, all!
